export const TRANSFER_TYPE_ALLOWANCE = 'TRANSFER_TYPE_ALLOWANCE';
export const TRANSFER_TYPE_TASK = 'TRANSFER_TYPE_TASK';
export const TRANSFER_TYPE_PRESENT = 'TRANSFER_TYPE_PRESENT';
export const TRANSFER_TYPE_DELETION = 'TRANSFER_TYPE_DELETION';

export const NOTIFICATION_STAGE_TASK_QUESTION = 'NOTIFICATION_STAGE_TASK_QUESTION';
export const NOTIFICATION_STAGE_TASK_GREAT = 'NOTIFICATION_STAGE_TASK_GREAT';
export const NOTIFICATION_STAGE_TASK_FINISH = 'NOTIFICATION_STAGE_TASK_FINISH';
export const NOTIFICATION_STAGE_ALLOWANCE_CLOUD = 'NOTIFICATION_STAGE_ALLOWANCE_CLOUD';
