export const SCREEN_HOME = 'SCREEN_HOME';
export const SCREEN_SETTINGS = 'SCREEN_SETTINGS';
export const SCREEN_LOGIN = 'SCREEN_LOGIN';
export const SCREEN_SET_PASSCODE = 'SCREEN_SET_PASSCODE';
export const SCREEN_WALLET = 'SCREEN_WALLET';
export const SCREEN_DASHBOARD = 'SCREEN_DASHBOARD';
export const SCREEN_TRANSACTIONS = 'SCREEN_TRANSACTIONS';
export const SCREEN_GAME = 'SCREEN_GAME';
export const SCREEN_MESSAGES = 'SCREEN_MESSAGES';
export const SCREEN_ESCROW = 'SCREEN_ESCROW';
export const SCREEN_TRANSFER = 'SCREEN_TRANSFER';
export const SCREEN_DEVICE_AUTH = 'SCREEN_DEVICE_AUTH';
export const SCREEN_CREATE_KEYS = 'SCREEN_CREATE_KEYS';
export const SCREEN_MNEMONIC = 'SCREEN_MNEMONIC';
export const SCREEN_RESTORE_KEYS = 'SCREEN_RESTORE_KEYS';
export const SCREEN_TOUCH_ID = 'SCREEN_TOUCH_ID';

export const SCREEN_CLAIM = 'SCREEN_CLAIM';

export const SCREEN_CLAIM_ICO = 'SCREEN_CLAIM_ICO';
export const SCREEN_CLAIM_ICO_INFO_B = 'SCREEN_CLAIM_ICO_INFO_B';
export const SCREEN_CLAIM_ICO_INFO_C = 'SCREEN_CLAIM_ICO_INFO_C';
export const SCREEN_CLAIM_ICO_ENTER_KEYS = 'SCREEN_CLAIM_ICO_ENTER_KEYS';
export const SCREEN_CLAIM_ICO_BALANCE = 'SCREEN_CLAIM_ICO_BALANCE';
export const SCREEN_CLAIM_ICO_ESTIMATE_GAS = 'SCREEN_CLAIM_ICO_ESTIMATE_GAS';
export const SCREEN_CLAIM_ICO_BURN = 'SCREEN_CLAIM_ICO_BURN';

export const SCREEN_CLAIM_AIRDROP = 'SCREEN_CLAIM_AIRDROP';
export const SCREEN_CLAIM_AIRDROP_ENTER_KEYS = 'SCREEN_CLAIM_AIRDROP_ENTER_KEYS';
export const SCREEN_CLAIM_AIRDROP_BALANCE = 'SCREEN_CLAIM_AIRDROP_BALANCE';
export const SCREEN_CLAIM_AIRDROP_CLAIM = 'SCREEN_CLAIM_AIRDROP_CLAIM';

export const SCREEN_CLAIM_VIP = 'SCREEN_CLAIM_VIP';
export const SCREEN_CLAIM_VIP_REGISTER = 'SCREEN_CLAIM_VIP_REGISTER';
export const SCREEN_CLAIM_VIP_VERIFY_EMAIL = 'SCREEN_CLAIM_VIP_VERIFY_EMAIL';
export const SCREEN_CLAIM_VIP_REQUEST_CODE = 'SCREEN_CLAIM_VIP_REQUEST_CODE';
export const SCREEN_CLAIM_VIP_VERIFY_CODE = 'SCREEN_CLAIM_VIP_VERIFY_CODE';
export const SCREEN_CLAIM_VIP_FINISH = 'SCREEN_CLAIM_VIP_FINISH';

export const SCREEN_SET_EMAIL = 'SCREEN_SET_EMAIL';
export const SCREEN_SET_CURRENCY = 'SCREEN_SET_CURRENCY';
export const SCREEN_CHANGE_PASSCODE = 'SCREEN_CHANGE_PASSCODE';
export const SCREEN_KID_SET_LOGIN = 'SCREEN_KID_SET_LOGIN';
export const SCREEN_KID_LOGIN = 'SCREEN_KID_LOGIN';
export const SCREEN_KID_DASHBOARD = 'SCREEN_KID_DASHBOARD';
export const SCREEN_KID_TRANSACTIONS = 'SCREEN_KID_TRANSACTIONS';
export const SCREEN_KID_GOAL_ADD = 'SCREEN_KID_GOAL_ADD';
export const SCREEN_KIDS_INTRO = 'SCREEN_KIDS_INTRO';
export const SCREEN_KIDS_PARENT_NICKNAME = 'SCREEN_KIDS_PARENT_NICKNAME';
export const SCREEN_KIDS_NUMBER_TO_ADD = 'SCREEN_KIDS_NUMBER_TO_ADD';
export const SCREEN_KIDS_ENTER_PROFILE = 'SCREEN_KIDS_ENTER_PROFILE';
export const SCREEN_TASKS_LIST = 'SCREEN_TASKS_LIST';
export const SCREEN_TASKS_ASSIGN = 'SCREEN_TASKS_ASSIGN';
export const SCREEN_ALLOWANCE_AMOUNT = 'SCREEN_ALLOWANCE_AMOUNT';
export const SCREEN_ALLOWANCE_INTERVAL = 'SCREEN_TASKS_ALLOWANCE';
