export default {
    piggy: require('./piggy.png'),
    tick: require('./tick.png'),
    code: require('./code.png'),
    touch: require('./touch.png'),
    keys: require('./keys.png'),
    secure: require('./secure.png'),
    address: require('./address.png'),
    vip: require('./vip.png'),
    eidoo: require('./eidoo.png'),
    settings: require('./settings.png'),
    messages: require('./messages.png'),
    transfer: require('./transfer.png'),
    coins: require('./coins.png'),
    family: require('./family.png'),
};
